DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE IF NOT EXISTS AUTHOR (
    ID_AUTHOR   VARCHAR(50) NOT NULL,
    FIRST_NAME  VARCHAR(50) NOT NULL,
    LAST_NAME   VARCHAR(50) NOT NULL,
    NICK_NAME    VARCHAR(50) NOT NULL,
    BIRTHDAY    TIMESTAMP   NOT NULL,
    ADRESSE     VARCHAR(50) NOT NULL
);

INSERT INTO AUTHOR
(ID_AUTHOR, FIRST_NAME, LAST_NAME, NICK_NAME, BIRTHDAY, ADRESSE)
VALUES
('UUID_1','BON','JEAN','Jambon','2000-01-01T00:00:00.000+01:00','10 rue de Paris, 75001, France');

INSERT INTO AUTHOR
(ID_AUTHOR, FIRST_NAME, LAST_NAME, NICK_NAME, BIRTHDAY, ADRESSE)
VALUES
('UUID_2','BOIS','COLOMBES','BOIS_COLOMBES','2010-01-01T00:00:00.000+01:00','20 rue de Paris, 75001, France');