DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE  IF EXISTS ROLE;

CREATE TABLE IF NOT EXISTS AUTHOR (
    ID_AUTHOR   VARCHAR(50) NOT NULL,
    FIRST_NAME  VARCHAR(50) NOT NULL,
    LAST_NAME   VARCHAR(50) NOT NULL,
    NICK_NAME    VARCHAR(50) NOT NULL,
    BIRTHDAY    TIMESTAMP   NOT NULL,
    ADRESSE     VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK (
    ID_BOOK     VARCHAR(50) NOT NULL,
    TITLE       VARCHAR(100) NOT NULL,
    AUTHOR_ID   VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ROLE (
    ID_ROLE    VARCHAR(255) NOT NULL PRIMARY KEY,
    ROLE_NAME    VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS MEMBER (
    ID_MEMBER         VARCHAR(255) NOT NULL PRIMARY KEY,
    USERNAME        VARCHAR(50) NOT NULL,
    PASSWORD        VARCHAR(50) NOT NULL
);

INSERT INTO AUTHOR
(ID_AUTHOR, FIRST_NAME, LAST_NAME, NICK_NAME, BIRTHDAY, ADRESSE)
VALUES
('UUID_1','BON','JEAN','Jambon','2000-01-01T00:00:00.000+01:00','10 rue de Paris, 75001, France');

INSERT INTO AUTHOR
(ID_AUTHOR, FIRST_NAME, LAST_NAME, NICK_NAME, BIRTHDAY, ADRESSE)
VALUES
('UUID_2','BOIS','COLOMBES','BOIS_COLOMBES','2010-01-01T00:00:00.000+01:00','20 rue de Paris, 75001, France');