DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS USER;

CREATE TABLE IF NOT EXISTS AUTHOR (
    ID_AUTHOR   VARCHAR(50) NOT NULL,
    FIRST_NAME  VARCHAR(50) NOT NULL,
    LAST_NAME   VARCHAR(50) NOT NULL,
    NICK_NAME   VARCHAR(50) NOT NULL,
    BIRTHDAY    TIMESTAMP   NOT NULL,
    ADRESSE     VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK (
    ID_BOOK     VARCHAR(50) NOT NULL,
    TITLE       VARCHAR(100) NOT NULL,
    AUTHOR_ID   VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER (
    ID_USER     VARCHAR(50) NOT NULL,
    USERNAME    VARCHAR(50) NOT NULL,
    PASSWORD    VARCHAR(50) NOT NULL
);
commit;