DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS BOOK;

CREATE TABLE IF NOT EXISTS AUTHOR (
    ID_AUTHOR   VARCHAR(50) NOT NULL,
    FIRST_NAME  VARCHAR(50) NOT NULL,
    LAST_NAME   VARCHAR(50) NOT NULL,
    NICK_NAME   VARCHAR(50) NOT NULL,
    BIRTHDAY    TIMESTAMP   NOT NULL,
    ADRESSE     VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK (
    ID_BOOK     VARCHAR(50) NOT NULL,
    TITLE       VARCHAR(50) NOT NULL,
    AUTHOR_ID   VARCHAR(50) NOT NULL
);

INSERT INTO AUTHOR
(ID_AUTHOR, FIRST_NAME, LAST_NAME, NICK_NAME, BIRTHDAY, ADRESSE)
VALUES
('UUID_0','FirstName0','LastName0','NickName0','2000-01-01T00:00:00.000+01:00','10 rue de Paris, 75001, France');

INSERT INTO AUTHOR
(ID_AUTHOR, FIRST_NAME, LAST_NAME, NICK_NAME, BIRTHDAY, ADRESSE)
VALUES
('UUID_1','FirstName1','LastName1','NickName1','2000-11-01T00:00:00.000+01:00','20 rue de Paris, 75001, France');

INSERT INTO AUTHOR
(ID_AUTHOR, FIRST_NAME, LAST_NAME, NICK_NAME, BIRTHDAY, ADRESSE)
VALUES
('UUID_2','FirstName2','LastName2','NickName2','2000-01-01T00:00:00.000+01:00','30 rue de Paris, 75001, France');

INSERT INTO BOOK
(ID_BOOK,TITLE,AUTHOR_ID)
VALUES
('ID_BOOK_0','Le seigneur des totos','UUID_0');

INSERT INTO BOOK
(ID_BOOK,TITLE,AUTHOR_ID)
VALUES
('ID_BOOK_1','Le grand voyage','UUID_1');

INSERT INTO BOOK
(ID_BOOK,TITLE,AUTHOR_ID)
VALUES
('ID_BOOK_2','Les fables','UUID_2');

commit;